version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
    - .env.docker
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASS}
     - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
          - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
    - .env.docker
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASS}
    ports:
      - "5050:80"
volumes:
  postgres_data: {}
